# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca43c18b81c7dc32a6f9753b8cad33a0e42bcd359dbe08b1d7051f8398ab98402218234387e30cd3cb35820e8b924d095dd628ab7d44a1ad30f2355d08d5d05f

test:
  secret_key_base: 050f132aed602007c6cf2420946cbb62aa4b8e4449e0f186755ccb684bead29a27fcb1a0a8917d1a49c58cd391928a1cc1b6f5d3d0069960dd4acae3eb121ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
